<?php

namespace AppBundle\Repository;

/**
 * emailRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class emailRepository extends \Doctrine\ORM\EntityRepository
{
}
