<?php

namespace AppBundle\Controller;

use Doctrine\DBAL\ConnectionException;
use Psr\Log\LoggerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Symfony\Component\HttpFoundation\File\Exception\FileException;
use Symfony\Component\HttpFoundation\Request;
use AppBundle\Entity\Event;
use AppBundle\Form\EventType;

/**
 * Class EventController
 * @package AppBundle\Controller
 * @Route("/event")
 */
class EventController extends Controller
{
    /**
     * @Route("/show", name="show_events")
     */
    public function showAction(LoggerInterface $logger)
    {
        try{
            $events=$this->getDoctrine()->getManager()->getRepository(Event::class)
                ->findBy(array("status"=> true));

        }catch (ConnectionException $exception){
            $logger->error($exception->getMessage());
        }
        return $this->render('@App/Event/show.html.twig', array(
            "events"=>$events
        ));

    }


    /**
     * @Route("/details/{id}", name="show_details_events")
     */
    public function showDetailsAction($id){
        $event=$this->getDoctrine()->getRepository(Event::class)->findOneBy(array('id'=>$id));
        return $this->render('@App/Event/details.html.twig', array(
            'event'=>$event
        ));
    }

    /**
     * @Route("/add", name="add_event")
     * @todo role admin
     */
    public function addAction(Request $request)
    {
        $event = new Event();// create new event object to set event from form

        //generate form
        $form = $this->createForm(EventType::class,$event,array(
            'action'=>$this->generateUrl('add_event')
        ));

//        handle requests from form page
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {//if form is submitted & valid
            $file = $event->getImage();//get image from $event

//            generate image name with extension
            $fileName = $this->generateUniqueFileName().'.'.$file->guessExtension();

            try {//upload image in the file web/uploads/event directory

                $file->move(
                    $this->getParameter('image_directory'),
                    $fileName
                );
            } catch (FileException $e) {
                // ... handle exception if something happens during file upload
            }
            $event->setImage($fileName);//set the new image name

            //persist the $event
            $em=$this->getDoctrine()->getManager();
            $em->persist($event);
            $em->flush();

            //redirect to evets page
            return $this->redirect($this->generateUrl('show_events'));
        }

        return $this->render('@App/Event/add.html.twig', array(
            'form' => $form->createView()));
    }

    /**
     * @return string
     *
     */
    private function generateUniqueFileName()
    {
        // md5() reduces the similarity of the file names generated by
        // uniqid(), which is based on timestamps
        return md5(uniqid());
    }

    /**
     * @Route("/delete")
     */
    public function deleteAction()
    {
//        TODO oussema : delete event
        return $this->render('AppBundle:Event:delete.html.twig', array(
            // ...
        ));
    }

    /**
     * @Route("/update/{id}", name="update_event")
     */
    public function updateAction(Request $request,$id)
    {
        $event=  $this->getDoctrine()->getRepository(Event::class)->find($id);

        if (empty($event)) {

            return $this->redirectToRoute('404NotFound');
        }

        //generate form
        $form = $this->createForm(EventType::class,$event,array(
            'action'=>$this->generateUrl('update_event')
        ));

        //        handle requests from form page
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {//if form is submitted & valid
            $file = $event->getImage();
            dump($event);
            die();
        }

            return $this->forward('show_events');
    }

    /**
     * @Route("/search",name="search event")
     */
    public function searchAction(){
//        TODO Oussema : search Event
        return $this->render('AppBundle:Event:update.html.twig', array(
            // ...
        ));
    }
}